"""UI strings for the AI Guide, merged into the shared tables without overriding existing entries."""
from app.i18n import UI_EL
from app.i18n_de import UI_DE

STRINGS: dict[str, tuple[str, str]] = {
    # English: (Greek, German)
    "AI Travel Guide": ("Ταξιδιωτικός οδηγός AI", "KI-Reiseplaner"),
    "Answer a few questions and get a day-by-day plan for Veria and Imathia, built from our listings.": (
        "Απαντήστε σε λίγες ερωτήσεις και λάβετε πρόγραμμα ανά ημέρα για τη Βέροια και την Ημαθία, από τις καταχωρίσεις μας.",
        "Beantworten Sie ein paar Fragen und erhalten Sie einen Tagesplan für Veria und Imathia aus unseren Einträgen.",
    ),
    "Plan my trip": ("Σχεδίασε το ταξίδι μου", "Reise planen"),
    "No account needed. Your answers are kept for two hours.": (
        "Δεν χρειάζεται λογαριασμός. Οι απαντήσεις σας κρατούνται για δύο ώρες.",
        "Kein Konto nötig. Ihre Antworten werden zwei Stunden gespeichert.",
    ),
    "Progress": ("Πρόοδος", "Fortschritt"),
    "Dates": ("Ημερομηνίες", "Reisedaten"),
    "Party": ("Συνταξιδιώτες", "Reisegruppe"),
    "Interests": ("Ενδιαφέροντα", "Interessen"),
    "Budget": ("Προϋπολογισμός", "Budget"),
    "Wishes": ("Επιθυμίες", "Wünsche"),
    "Review": ("Έλεγχος", "Übersicht"),
    "When are you visiting?": ("Πότε θα έρθετε;", "Wann kommen Sie?"),
    "Arrival": ("Άφιξη", "Anreise"),
    "Departure": ("Αναχώρηση", "Abreise"),
    "Up to 7 days.": ("Έως 7 ημέρες.", "Bis zu 7 Tage."),
    "Who is travelling?": ("Ποιοι ταξιδεύουν;", "Wer reist?"),
    "Solo": ("Μόνος/η", "Allein"),
    "Couple": ("Ζευγάρι", "Paar"),
    "Family": ("Οικογένεια", "Familie"),
    "Group": ("Παρέα", "Gruppe"),
    "What interests you?": ("Τι σας ενδιαφέρει;", "Was interessiert Sie?"),
    "Heritage & archaeology": ("Κληρονομιά & αρχαιολογία", "Kulturerbe & Archäologie"),
    "Churches & monasteries": ("Εκκλησίες & μονές", "Kirchen & Klöster"),
    "Food & cafés": ("Φαγητό & καφέ", "Essen & Cafés"),
    "Nature & hiking": ("Φύση & πεζοπορία", "Natur & Wandern"),
    "Winter & skiing": ("Χειμώνας & σκι", "Winter & Skifahren"),
    "What is your budget?": ("Ποιος είναι ο προϋπολογισμός σας;", "Wie hoch ist Ihr Budget?"),
    "Low": ("Χαμηλός", "Niedrig"),
    "Mid": ("Μεσαίος", "Mittel"),
    "High": ("Υψηλός", "Hoch"),
    "Anything else we should know?": ("Κάτι άλλο που πρέπει να ξέρουμε;", "Sonst noch etwas?"),
    "Optional wishes": ("Προαιρετικές επιθυμίες", "Optionale Wünsche"),
    "e.g. vegetarian food, no long walks, sunset views": (
        "π.χ. χορτοφαγικό φαγητό, όχι μεγάλες διαδρομές, θέα στο ηλιοβασίλεμα",
        "z. B. vegetarisch, keine langen Wege, Sonnenuntergang",
    ),
    "Back": ("Πίσω", "Zurück"),
    "Continue": ("Συνέχεια", "Weiter"),
    "Review your trip": ("Έλεγχος ταξιδιού", "Reise überprüfen"),
    "Surprise me": ("Εκπλήξτε με", "Überrasch mich"),
    "Generate itinerary": ("Δημιουργία προγράμματος", "Reiseplan erstellen"),
    "This can take up to a minute.": ("Μπορεί να διαρκέσει έως ένα λεπτό.", "Das kann bis zu einer Minute dauern."),
    "Your Veria itinerary": ("Το πρόγραμμά σας στη Βέροια", "Ihr Reiseplan für Veria"),
    "Print / Save as PDF": ("Εκτύπωση / PDF", "Drucken / als PDF"),
    "Regenerate": ("Νέα πρόταση", "Neu erstellen"),
    "Start over": ("Από την αρχή", "Neu beginnen"),
    "Day": ("Ημέρα", "Tag"),
    "Generated by AI from VeriaGuide listings. Please check opening hours before you go.": (
        "Δημιουργήθηκε με AI από τις καταχωρίσεις του VeriaGuide. Ελέγξτε τα ωράρια πριν πάτε.",
        "Mit KI aus VeriaGuide-Einträgen erstellt. Bitte Öffnungszeiten vorab prüfen.",
    ),
    "You have planned a lot of trips": ("Έχετε σχεδιάσει πολλά ταξίδια", "Sie haben viele Reisen geplant"),
    "Please wait a while before generating another itinerary.": (
        "Περιμένετε λίγο πριν δημιουργήσετε νέο πρόγραμμα.",
        "Bitte warten Sie etwas, bevor Sie einen neuen Plan erstellen.",
    ),
    "We could not find matching places": ("Δεν βρέθηκαν κατάλληλα μέρη", "Keine passenden Orte gefunden"),
    "Try choosing different interests.": ("Δοκιμάστε άλλα ενδιαφέροντα.", "Wählen Sie andere Interessen."),
    "Something went wrong while planning": ("Κάτι πήγε στραβά στον σχεδιασμό", "Bei der Planung ist etwas schiefgelaufen"),
    "Our trip planner could not finish this time. Your answers are saved, so you can simply try again.": (
        "Ο σχεδιαστής δεν ολοκλήρωσε αυτή τη φορά. Οι απαντήσεις σας έχουν αποθηκευτεί, δοκιμάστε ξανά.",
        "Der Planer konnte diesmal nicht fertig werden. Ihre Antworten sind gespeichert, versuchen Sie es einfach erneut.",
    ),
    "Try again": ("Δοκιμάστε ξανά", "Erneut versuchen"),
    "Change interests": ("Αλλαγή ενδιαφερόντων", "Interessen ändern"),
    "Please choose valid dates.": ("Επιλέξτε έγκυρες ημερομηνίες.", "Bitte gültige Daten wählen."),
    "Trips can be at most 7 days.": ("Το ταξίδι μπορεί να είναι έως 7 ημέρες.", "Reisen dürfen höchstens 7 Tage dauern."),
    "Please choose who is travelling.": ("Επιλέξτε ποιοι ταξιδεύουν.", "Bitte wählen Sie, wer reist."),
    "Please choose a budget.": ("Επιλέξτε προϋπολογισμό.", "Bitte wählen Sie ein Budget."),
}

for _en, (_el, _de) in STRINGS.items():
    UI_EL.setdefault(_en, _el)
    UI_DE.setdefault(_en, _de)
